message(STATUS "in module1 CMakeLists.txt")
include_directories(./include)
aux_source_directory(./src DIR_MODULE1_SRCS)
#message(STATUS "DIR_MODULE1_SRCS: ${DIR_MODULE1_SRCS}")
#set(LIBRARY_OUTPUT_PATH ${PROJECT_BINARY_DIR}/mylib)
#add_library(module1_share SHARED ${DIR_MODULE1_SRCS})
add_library(module1_static STATIC ${DIR_MODULE1_SRCS})
#set_target_properties(module1_share PROPERTIES OUTPUT_NAME "hello")
set_target_properties(module1_static PROPERTIES OUTPUT_NAME "module1")